### ISSUE TITLE
pytest-postgresql 2.0.0 broken on macOS (AttributeError: module 'select' has no attribute 'poll')

### ISSUE THREAD

**Issue by lpsinger** [ClearcodeHQ/pytest-postgresql#232]
### What action do you want to perform

I have a minimal test file, `test_postgres.py`:

```python
def test_postgres(postgresql_proc):
    pass
```

and I run `pytest test_postgres.py` on macOS 10.14.6.

### What are the results

With pytest-postgresql I get the following error message.

This is broken in pytest-postgresql 2.0.0. If I downgrade to pytest-postgresql <= 1.4.1 and mirakuru <= 1.1.0, it's not broken.

```
(test) bash-3.2$ pytest test_postgres.py 
Traceback (most recent call last):
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/config/__init__.py", line 208, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/hooks.py", line 289, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/manager.py", line 87, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/manager.py", line 81, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/config/__init__.py", line 716, in pytest_cmdline_parse
    self.parse(args)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/config/__init__.py", line 924, in parse
    self._preparse(args, addopts=addopts)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/config/__init__.py", line 870, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pluggy/manager.py", line 292, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 90, in load
    module = import_module(match.group('module'))
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pytest_postgresql/plugin.py", line 21, in <module>
    from pytest_postgresql import factories
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pytest_postgresql/factories.py", line 33, in <module>
    from pytest_postgresql.executor import PostgreSQLExecutor
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/pytest_postgresql/executor.py", line 28, in <module>
    from mirakuru import TCPExecutor
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/mirakuru/__init__.py", line 24, in <module>
    from mirakuru.output import OutputExecutor
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/mirakuru/output.py", line 30, in <module>
    class OutputExecutor(SimpleExecutor):
  File "/Users/lpsinger/.local/share/virtualenvs/test-6C_DLGjE/lib/python3.7/site-packages/mirakuru/output.py", line 107, in OutputExecutor
    def _wait_for_output(self, *polls: Tuple[select.poll, IO[Any]]) -> bool:
AttributeError: module 'select' has no attribute 'poll'
```

### What are the expected results

```
(test) bash-3.2$ pytest test_postgres.py 
============================= test session starts ==============================
platform darwin -- Python 3.7.4, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
rootdir: /private/tmp/test
plugins: postgresql-1.4.1
collected 1 item                                                               

test_postgres.py .                                                       [100%]

============================== 1 passed in 1.20s ===============================
```

**Comment by fizyk** [comment]
@lpsinger I'm a bit puzzled by this, since mirakuru is being tested on osx: 
https://travis-ci.org/ClearcodeHQ/mirakuru/jobs/572609552

So could this issue be related to the way the python is installed on macos in your case, and how it is installed on travis-ci?

**Comment by fizyk** [comment]
@lpsinger never the less, the issue is both with mirakuru and mac os built-in python interpreter. I'd honestly welcome input and a fix from someone who actually owns osx, than me guess-fixing it :)

**Comment by lpsinger** [comment]
What confuses me is that it looks like `select.poll` has been in miraku for a very long time. How does this even work with the old versions of miraku and pytest-postgresql that I have pinned?

**Comment by fizyk** [comment]
Yup, that's why I'd prefer to have someone with macbook to debug it. I'll try to run tests on osx on travis, but as I can see, everything works there...

**Comment by lpsinger** [comment]
From `selectmodule.c` in cpython:

```c
#ifdef __APPLE__
/*
 * On some systems poll() sets errno on invalid file descriptors. We test
 * for this at runtime because this bug may be fixed or introduced between
 * OS releases.
 */
static int select_have_broken_poll(void)
{
    int poll_test;
    int filedes[2];

    struct pollfd poll_struct = { 0, POLLIN|POLLPRI|POLLOUT, 0 };

    /* Create a file descriptor to make invalid */
    if (pipe(filedes) < 0) {
        return 1;
    }
    poll_struct.fd = filedes[0];
    close(filedes[0]);
    close(filedes[1]);
    poll_test = poll(&poll_struct, 1, 0);
    if (poll_test < 0) {
        return 1;
    } else if (poll_test == 0 && poll_struct.revents != POLLNVAL) {
        return 1;
    }
    return 0;
}
#endif /* __APPLE__ */
```

So it looks like `select.poll` is baked in to every CPython build on macOS, but may be disabled at run time.

**Comment by fizyk** [comment]
From what I've found I can migrate to use `select.select` https://github.com/ClearcodeHQ/mirakuru/issues/331#issuecomment-527129011 although staying with poll/kqueue would be the best approach I think. (Maybe staying with poll and fallback to select for macos...)

**Comment by fizyk** [comment]
https://stackoverflow.com/questions/19740471/cannot-use-python-select-poll-in-mac-os

**Comment by fizyk** [comment]
@lpsinger could you try this: https://github.com/ClearcodeHQ/mirakuru/pull/333 ?

**Comment by fizyk** [comment]
@lpsinger please check mirakuru 2.1.0

**Comment by lpsinger** [comment]
Yes, works now. Thank you!
