### ISSUE TITLE
Does not work in some earlier versions of python 3.5

### ISSUE THREAD

**Issue by rschwiebert** [ClearcodeHQ/pytest-postgresql#238]
### What action do you want to perform
I want to use the postgresql fixture in a test. I have python 3.5.2 and pytest-postgresql 2.1.0.

### What are the results
```Traceback (most recent call last):
  File "/opt/venvs/test/bin/pytest", line 10, in <module>
    sys.exit(main())
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 208, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/helpconfig.py", line 89, in pytest_cmdline_parse
    config = outcome.get_result()
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 719, in pytest_cmdline_parse
    self.parse(args)
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 927, in parse
    self._preparse(args, addopts=addopts)
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/config/__init__.py", line 873, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/opt/venvs/test/lib/python3.5/site-packages/pluggy/manager.py", line 297, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/venvs/test/lib/python3.5/site-packages/importlib_metadata/__init__.py", line 92, in load
    module = import_module(match.group('module'))
  File "/opt/venvs/test/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/opt/venvs/test/lib/python3.5/site-packages/pytest_postgresql/plugin.py", line 21, in <module>
    from pytest_postgresql import factories
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/opt/venvs/test/lib/python3.5/site-packages/pytest_postgresql/factories.py", line 28, in <module>
    from pytest_postgresql.janitor import DatabaseJanitor, psycopg2
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/opt/venvs/test/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 140, in exec_module
    exec(co, module.__dict__)
  File "/opt/venvs/test/lib/python3.5/site-packages/pytest_postgresql/janitor.py", line 23, in <module>
    class DatabaseJanitor:
  File "/opt/venvs/test/lib/python3.5/site-packages/pytest_postgresql/janitor.py", line 94, in DatabaseJanitor
    exc_type: Optional[Type[BaseException]],
  File "/usr/lib/python3.5/typing.py", line 649, in __getitem__
    return Union[arg, type(None)]
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 1077, in __subclasscheck__
    if super().__subclasscheck__(cls):
  File "/opt/venvs/test/lib/python3.5/abc.py", line 225, in __subclasscheck__
    for scls in cls.__subclasses__():
TypeError: descriptor '__subclasses__' of 'type' object needs an argument
```

### What are the expected results
Including `postgresql` fixture should not cause this exception(?)

Upon a little further digging, I found that the version of `mirakuru` installed requires python 3.6 or later.   Downgrading mirikuru to 1.1.0 and pytest-postgresql to 1.4.1 got things to work, but at the cost of installing a version of mirakuru that is incompatible according to the specifications.

In this commit: https://github.com/ClearcodeHQ/pytest-postgresql/commit/76e6605e19450fe37faabf8679332d66a597529b I see someone pinning to <2.1.0 for python3.5, possibly to fix this. However, 2.0.1 appears to be the only version that suits the hard-coded requirements, but it doesn't fix the problem.  Downgrading `mirakuru` to 1.1.0 eliminated the traceback I reported above, but still threw the same exception at a different point in code.

**Comment by fizyk** [comment]
@rschwiebert what do you use to install dependencies? mirakuru isn't pinned in the **setup.py** and the commit you linked is only showing the requires file used for tests explicitly.

That's how the instal;ation should behave. see here: https://travis-ci.org/ClearcodeHQ/pytest-postgresql/jobs/588819523

**Comment by fizyk** [comment]
@rschwiebert I'm pretty sure it should work properly, after adventure with mirakuru 2.0.0 here: https://github.com/ClearcodeHQ/mirakuru/issues/319
*pip* should pick the only mirakuru version that fits python 3.5 and is version 2 or higher, which is 2.0.1.

**Comment by rschwiebert** [comment]
> @rschwiebert what do you use to install dependencies? mirakuru isn't pinned in the **setup.py** and the commit you linked is only showing the requires file used for tests explicitly.

I had just used `pip install pytest-postgresql`.  Here are steps to reproduce:

I'm working on an Ubuntu 16.04 image, so python 3.5.2 is what ships with it.

1. created a python 3.5.2 virtualenv using virtualenv, and sourced it
1. pip install pytest-postgresql. The output is:  ```Successfully installed atomicwrites-1.3.0 attrs-19.1.0 importlib-metadata-0.23 mirakuru-2.0.1 more-itertools-7.2.0 packaging-19.2 pathlib2-2.3.4 pluggy-0.13.0 port-for-0.4 psutil-5.6.3 py-1.8.0 pyparsing-2.4.2 pytest-5.1.3 pytest-postgresql-2.1.0 six-1.12.0 wcwidth-0.1.7 zipp-0.6.0```
1.  Wrote a test in a test file that looks like this:   `def test_something(postgresql): pass`
1.  Running pytest on that file results in the traceback given above.

**Comment by rschwiebert** [comment]
Possibly updating python3 would fix the problem, but I don't have that option in my context.

If it's not going to be supported, it can just be restricted to a higher version of python>=3.5.6, right?

I don't *have* to have this working with 3.5.2, I just wanted to capture the compatibility problem as-is.

**Comment by fizyk** [comment]
@rschwiebert I'll have mirakuru version for you to run today. Should be 2.0.2

**Comment by fizyk** [comment]
@rschwiebert Mirakuru 2.0.2 should be out. Marking this issue as closed. Let me know in case it's still not fixed.
