### ISSUE TITLE
Is this expected?

### ISSUE THREAD

**Issue by DmitryLitvintsev** [ClearcodeHQ/pytest-postgresql#325]
### What action do you want to perform

I want to create database on  the fly to perform multiple unit tests against it. I am trying this :

```
>>> from pytest_postgresql.factories import DatabaseJanitor
>>> DatabaseJanitor('postgres', 'localhost', 1234, 'foo', 0.0).init()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/litvinse/venv/lib/python3.6/site-packages/pytest_postgresql/janitor.py", line 57, in init
    with self.cursor() as cur:
  File "/usr/lib64/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/litvinse/venv/lib/python3.6/site-packages/pytest_postgresql/janitor.py", line 87, in cursor
    port=self.port,
  File "/home/litvinse/venv/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 12345?

```
Is this expected? The doc is not quite clear to me. Looking at the code of janitor.py indeed I do not see any code spawning postgersql process. So what is the proper way to do it.

**Comment by fizyk** [comment]
@DmitryLitvintsev, use fixtures, not the janitor, janitor works on already running postges instance, (see for example warehouse use https://github.com/pypa/warehouse/blob/master/tests/conftest.py#L135 )

The intention is to use fixtures, Janitor is mostly a convenience construct after I saw the warehouse's use of previous functions.
