### ISSUE TITLE
AttributeError when importing if psycopg2 is not installed

### ISSUE THREAD

**Issue by di** [ClearcodeHQ/pytest-postgresql#426]
### What action do you want to perform
```python
import pytest_postgresql.factories
```

### What are the results
```
root@48d17a54a3fa:/# python -c "import pytest_postgresql.factories"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pytest_postgresql/factories/__init__.py", line 20, in <module>
    from pytest_postgresql.factories.process import postgresql_proc
  File "/usr/local/lib/python3.9/site-packages/pytest_postgresql/factories/process.py", line 31, in <module>
    from pytest_postgresql.janitor import DatabaseJanitor
  File "/usr/local/lib/python3.9/site-packages/pytest_postgresql/janitor.py", line 11, in <module>
    from pytest_postgresql.retry import retry
  File "/usr/local/lib/python3.9/site-packages/pytest_postgresql/retry.py", line 9, in <module>
    def retry(func, timeout: int = 60, possible_exception=psycopg2.OperationalError):
AttributeError: 'bool' object has no attribute 'OperationalError'
```

### What are the expected results
A successful import.

**Comment by fizyk** [comment]
+ A CI action to keep it in check

**Comment by fizyk** [comment]
try v3.0.1
